kind: Secret
apiVersion: v1
metadata:
  name: wordpress-mariadb
  namespace: wordpress
  labels:
    app: wordpress
data:
  database-name: d29yZHByZXNz
  database-password: d29yZHByZXNz
  database-root-password: d29yZHByZXNz
  database-user: bXlzcWw=
type: Opaque

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-persistent-storage
  namespace: wordpress
  labels:
    app: wordpress
    tier: frontend
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ocp-trident

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-mariadb-persistent-storage
  namespace: wordpress
  labels:
    app: wordpress
    tier: mariadb
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ocp-trident

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mariadb 
  namespace: wordpress
  labels:                 
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mariadb
  type: ClusterIP

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: wordpress-mariadb
  namespace: wordpress
  labels:
    app: wordpress
spec:
  strategy:
    type: Recreate
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - mariadb
        from:
          kind: ImageStreamTag
          namespace: openshift
          name: 'mariadb:10.3-el8'
    - type: ConfigChange
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: mariadb
  template:
    metadata:
      labels:
        app: wordpress
        tier: mariadb
    spec:
      volumes:
        - name: wordpress-mariadb
          persistentVolumeClaim:
            claimName: wordpress-mariadb-persistent-storage
      securityContext:
        fsGroup: 1000950000
        seLinuxOptions:
          level: s0:c25,c10
      containers:
        - name: wordpress-mariadb
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: wordpress-mariadb
                  key: database-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-mariadb
                  key: database-password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-mariadb
                  key: database-root-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: wordpress-mariadb
                  key: database-name
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - name: wordpress-mariadb
              mountPath: /var/lib/mysql/data
          securityContext:
            runAsUser: 1000950000
          image: registry.redhat.io/rhel8/mariadb-103@sha256:ba604ff057dcd9f70043729f191eb2d2889e74777c305e39dba583bda6946142

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mariadb
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-mariadb
              key: database-root-password
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: wordpress-mariadb
              key: database-name
        - name: WORDPRESS_DB_USER
          value: root
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: "/var/www/html"          
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-persistent-storage

---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: wordpress-demo
  namespace: wordpress
  labels:
    app: wordpress
spec:
  host: wordpress-demo-wordpress.apps.ocp-vmw.cie.netapp.com
  to:
    kind: Service
    name: wordpress
    weight: 100
  port:
    targetPort: 80
  wildcardPolicy: None
